version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/event-booking

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    container_name: event-service
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/event-booking

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/event-booking

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    ports:
      - "5003:5003"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - event-service
      - booking-service

volumes:
  mongo_data:
